<?php

declare(strict_types=1);

namespace App\Modules\Integrations\Definitions;

use App\Modules\Integrations\DTO\CheckResult;
use App\Modules\Integrations\DTO\FieldSpec;
use App\Modules\Integrations\DTO\IntegrationConfig;
use App\Modules\Integrations\Enums\IntegrationGroup;
use Illuminate\Http\Client\PendingRequest;
use Illuminate\Http\Client\Response;

/**
 * Telegram bot (business account). Check: read-only getMe.
 * The request URL contains the token, so neither the URL nor exception texts are ever logged or returned.
 */
final class TelegramBusinessDefinition extends AbstractHttpCheckedDefinition
{
    public const string API = 'https://api.telegram.org';

    public const string TOKEN_PATTERN = '/^\d+:[A-Za-z0-9_-]+$/';

    public function key(): string
    {
        return 'telegram_business';
    }

    public function group(): IntegrationGroup
    {
        return IntegrationGroup::Messengers;
    }

    public function fields(): array
    {
        return [
            FieldSpec::secret('bot_token'),
            // Random secret for the X-Telegram-Bot-Api-Secret-Token header; generated by "Register webhook"
            // (Channels module), may be rotated by registering again.
            FieldSpec::secret('webhook_secret', required: false),
        ];
    }

    public function check(IntegrationConfig $config): CheckResult
    {
        $token = $config->secret('bot_token');
        if ($token === null) {
            return CheckResult::error('missing_secret:bot_token');
        }
        // Validate before the token is put into a URL: a stray space/newline would make the HTTP library
        // throw an exception whose message contains the whole URL (and so the token).
        if (preg_match(self::TOKEN_PATTERN, $token) !== 1) {
            return CheckResult::error('invalid_token');
        }
        $url = self::API.'/bot'.$token.'/getMe';
        $response = $this->probe($url, static fn (PendingRequest $r): Response => $r->get($url));
        if ($response instanceof CheckResult) {
            return $response;
        }

        if ($response->successful() && $response->json('ok') === true) {
            return CheckResult::connected();
        }

        return CheckResult::error($response->status() === 401 ? 'unauthorized' : 'http_'.$response->status());
    }
}
