<?php

declare(strict_types=1);

namespace App\Modules\Recruiting\Enums;

/** Where a touchpoint happened. "system" = generated by the product (stage change, link), never counts as a touch. */
enum Channel: string
{
    case Call = 'call';
    case Telegram = 'telegram';
    case Whatsapp = 'whatsapp';
    case Viber = 'viber';
    case Email = 'email';
    case Note = 'note';
    case Meeting = 'meeting';
    case System = 'system';

    /** Channels a user may log by hand (POST /api/candidates/{id}/touchpoints). */
    public const array MANUAL = [self::Note, self::Call, self::Meeting, self::Telegram, self::Whatsapp, self::Viber, self::Email];

    /** @return list<string> */
    public static function values(): array
    {
        return array_map(static fn (self $c): string => $c->value, self::cases());
    }

    /** @return list<string> */
    public static function manualValues(): array
    {
        return array_map(static fn (self $c): string => $c->value, self::MANUAL);
    }

    /** A real contact with the candidate (updates last_touch_at); system events do not. */
    public function isTouch(): bool
    {
        return $this !== self::System;
    }
}
