<?php

declare(strict_types=1);

namespace App\Modules\Channels\Adapters;

use App\Modules\Channels\Contracts\ChannelAdapter;
use App\Modules\Channels\Contracts\MessageSender;
use App\Modules\Channels\Contracts\WebhookRegistrar;
use App\Modules\Channels\DTO\DemoSeed;
use App\Modules\Channels\DTO\IncomingEvent;
use App\Modules\Channels\DTO\OutgoingMessage;
use App\Modules\Channels\DTO\SentMessage;
use App\Modules\Channels\Enums\EventKind;
use App\Modules\Channels\Enums\WebhookAuth;
use App\Modules\Channels\Exceptions\ChannelException;
use App\Modules\Channels\Support\Payload;
use App\Modules\Channels\Support\ProviderHttp;
use App\Modules\Integrations\Definitions\TelegramBusinessDefinition;
use App\Modules\Integrations\DTO\IntegrationConfig;
use App\Modules\Recruiting\Enums\Channel;
use App\Modules\Recruiting\Enums\Direction;
use Illuminate\Http\Request;
use Illuminate\Support\Carbon;

/**
 * Telegram Bot API with Telegram Business: the recruiter connects the bot to their business account, the bot receives
 * the recruiter's private chats (business_message) and may reply in them (sendMessage + business_connection_id).
 * Webhook auth: X-Telegram-Bot-Api-Secret-Token = vault "webhook_secret" (generated by "Register webhook").
 * Direction: in private chats chat.id is the other party, so from.id === chat.id → from the candidate (in),
 * otherwise the business owner (or the bot) wrote (out). thread = "{business_connection_id}:{chat.id}".
 */
final readonly class TelegramBusinessAdapter implements ChannelAdapter, MessageSender, WebhookRegistrar
{
    public const string SECRET_HEADER = 'X-Telegram-Bot-Api-Secret-Token';

    /** @var list<string> */
    public const array ALLOWED_UPDATES = ['business_message', 'edited_business_message', 'business_connection'];

    /** @var list<string> media keys shown as a placeholder when a message has no text */
    private const array MEDIA = ['photo', 'video', 'voice', 'audio', 'document', 'sticker', 'video_note', 'contact', 'location'];

    public function __construct(private ProviderHttp $http) {}

    public function key(): string
    {
        return 'telegram_business';
    }

    public function channel(): Channel
    {
        return Channel::Telegram;
    }

    public function auth(): WebhookAuth
    {
        return WebhookAuth::HeaderSecret;
    }

    public function verify(Request $request, IntegrationConfig $config): bool
    {
        $secret = $config->secret('webhook_secret');
        $given = $request->header(self::SECRET_HEADER);

        return $secret !== null && is_string($given) && hash_equals($secret, $given);
    }

    public function parse(array $payload, IntegrationConfig $config): array
    {
        if (is_array($payload['business_connection'] ?? null)) {
            $connection = $payload['business_connection'];

            return [new IncomingEvent(EventKind::Status, Direction::In, Carbon::now(), meta: [
                'status' => ($connection['is_enabled'] ?? false) === true ? 'business_connected' : 'business_disconnected',
            ])];
        }
        $edited = is_array($payload['edited_business_message'] ?? null);
        $message = Payload::arr($payload[$edited ? 'edited_business_message' : 'business_message'] ?? null);
        $connectionId = Payload::str($message, ['business_connection_id']);
        $messageId = Payload::str($message, ['message_id']);
        $chatId = Payload::str($message, ['chat.id']);
        if ($message === [] || $connectionId === null || $messageId === null || $chatId === null) {
            return [];
        }

        $fromId = Payload::str($message, ['from.id']);
        $incoming = $fromId === $chatId && ! isset($message['sender_business_bot']);
        $other = Payload::arr($incoming ? ($message['from'] ?? null) : ($message['chat'] ?? null));
        $username = Payload::str($other, ['username']);
        $name = trim((Payload::str($other, ['first_name']) ?? '').' '.(Payload::str($other, ['last_name']) ?? ''));
        $meta = array_filter([
            'sender_name' => $name !== '' ? $name : null,
            'edited' => $edited ? true : null,
        ], static fn (mixed $v): bool => $v !== null);

        $externalId = $connectionId.':'.$messageId;
        if ($edited) {
            $externalId .= ':edit:'.(Payload::str($message, ['edit_date']) ?? '0');
        }

        return [new IncomingEvent(
            kind: EventKind::Message,
            direction: $incoming ? Direction::In : Direction::Out,
            occurredAt: Payload::time($message, [$edited ? 'edit_date' : 'date', 'date'], Carbon::now()),
            contact: $username !== null ? '@'.$username : null,
            body: Payload::str($message, ['text', 'caption']) ?? $this->mediaPlaceholder($message),
            externalId: $externalId,
            thread: $connectionId.':'.$chatId,
            meta: $meta,
        )];
    }

    public function demoPayload(DemoSeed $seed, IntegrationConfig $config): array
    {
        $user = ['id' => $seed->numericId, 'is_bot' => false, 'first_name' => $seed->senderName];
        if ($seed->telegramUsername !== null) {
            $user['username'] = $seed->telegramUsername;
        }

        return [
            'update_id' => $seed->numericId,
            'business_message' => [
                'business_connection_id' => 'demo-'.$seed->uid,
                'message_id' => $seed->numericId,
                'from' => $user,
                'chat' => ['type' => 'private'] + $user,
                'date' => $seed->at->getTimestamp(),
                'text' => $seed->text,
            ],
        ];
    }

    public function acknowledge(): array
    {
        return ['ok' => true];
    }

    public function send(OutgoingMessage $message, IntegrationConfig $config): SentMessage
    {
        $thread = $message->recipient->thread;
        if ($thread === null || ! str_contains($thread, ':')) {
            throw ChannelException::noConversation();
        }
        [$connectionId, $chatId] = explode(':', $thread, 2);
        $messageId = $this->sendMessage($config, [
            'business_connection_id' => $connectionId,
            'chat_id' => $chatId,
            'text' => $message->text,
        ]);

        return new SentMessage($connectionId.':'.$messageId, $thread);
    }

    public function sendTest(string $to, string $text, IntegrationConfig $config): SentMessage
    {
        if (preg_match('/^-?\d{1,20}$/', $to) !== 1) {
            throw ChannelException::invalidRecipient();
        }

        return new SentMessage('test:'.$this->sendMessage($config, ['chat_id' => $to, 'text' => $text]));
    }

    public function generatedSecret(): string
    {
        return 'webhook_secret';
    }

    public function register(string $url, ?string $secret, IntegrationConfig $config): void
    {
        $response = $this->http->postJson($this->method($config, 'setWebhook'), [
            'url' => $url,
            'secret_token' => $secret,
            'allowed_updates' => self::ALLOWED_UPDATES,
        ]);
        if (! $response->successful() || $response->json('ok') !== true) {
            throw ChannelException::sendFailed();
        }
    }

    /** @param  array<string, mixed>  $body */
    private function sendMessage(IntegrationConfig $config, array $body): string
    {
        $response = $this->http->postJson($this->method($config, 'sendMessage'), $body);
        $id = $response->json('result.message_id');
        if (! $response->successful() || $response->json('ok') !== true || ! is_int($id)) {
            // 400 "chat not found" / 403 "bot was blocked" or the business connection has no reply right.
            throw in_array($response->status(), [400, 403], true) ? ChannelException::noConversation() : ChannelException::sendFailed();
        }

        return (string) $id;
    }

    private function method(IntegrationConfig $config, string $method): string
    {
        $token = $config->secret('bot_token');
        // Validated before it goes into the URL: a malformed token would end up in an exception message.
        if ($token === null || preg_match(TelegramBusinessDefinition::TOKEN_PATTERN, $token) !== 1) {
            throw ChannelException::notConnected();
        }

        return TelegramBusinessDefinition::API.'/bot'.$token.'/'.$method;
    }

    /** @param  array<array-key, mixed>  $message */
    private function mediaPlaceholder(array $message): ?string
    {
        foreach (self::MEDIA as $key) {
            if (isset($message[$key])) {
                return '['.$key.']';
            }
        }

        return null;
    }
}
