<?php

declare(strict_types=1);

namespace App\Modules\Scripts\Models;

use App\Models\User;
use App\Modules\Recruiting\Models\Application;
use App\Modules\Recruiting\Models\Candidate;
use App\Modules\Scripts\Enums\TaskType;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Support\Carbon;

/**
 * A to-do of a recruiter: a follow-up generated by script rules or a manual one.
 *
 * @property int $id
 * @property int $assignee_id
 * @property int|null $candidate_id
 * @property int|null $application_id
 * @property TaskType $type
 * @property string $title
 * @property Carbon $due_at
 * @property Carbon|null $done_at
 * @property string|null $template_key
 * @property string|null $rule_key
 * @property Carbon|null $created_at
 * @property Carbon|null $updated_at
 * @property-read User $assignee
 * @property-read Candidate|null $candidate
 * @property-read Application|null $application
 */
final class Task extends Model
{
    protected $fillable = [
        'assignee_id', 'candidate_id', 'application_id', 'type', 'title', 'due_at', 'done_at', 'template_key', 'rule_key',
    ];

    /** @return BelongsTo<User, $this> */
    public function assignee(): BelongsTo
    {
        return $this->belongsTo(User::class, 'assignee_id');
    }

    /** @return BelongsTo<Candidate, $this> */
    public function candidate(): BelongsTo
    {
        return $this->belongsTo(Candidate::class);
    }

    /** @return BelongsTo<Application, $this> */
    public function application(): BelongsTo
    {
        return $this->belongsTo(Application::class);
    }

    /** @return array<string, string> */
    protected function casts(): array
    {
        return ['type' => TaskType::class, 'due_at' => 'datetime', 'done_at' => 'datetime'];
    }
}
